[model]
appliances = ["fridge", "dish_washer", "washing_machine"]
train_size = 0.8  # Train size, relative to 1
valid_size = 0.1  # Validation size, relative to 1
period = "1min"  # Time period of the sequence
input_len = 510  # Number of records per data point
border = 15  # Overlap between series
max_power = 10000.0  # Maximum load power, in watts
power_scale = 2000.0  # Power value by which we divide the load, normalizing it
name = "ConvModel"  # Model to use
batch_size = 32  # Batch size of the model
epochs = 300  # Training epochs
patience = 300  # Early stopping
init_features = 32
learning_rate = 1.0e-4
dropout = 0.1
regression_w = 1.0
classification_w = 0.0
num_models = 5 # Number of models to train. Their scores are then averaged

[model.threshold]
method = "vs"  # Thresholding method to use:
# 'vs': Variance-Sensitive. Applies k-means and uses the std of each
# cluster to move the threshold accordingly.
# 'mp': Middle-Point. Applies k-means and sets the threshold in the
# middle of the two cluster centroids.
# 'at': Activation-Time. Takes the thresholds and activation times defined by J. Kelly.
#'custom': Use custom thresholding, by providing the (!) parameters.
num_status = 2

[model.dates.ukdale]  # Date range for each building
1 = ["2013-04-12", "2014-12-15"]
2 = ["2013-05-22", "2013-10-03 6:16"]
5 =["2014-04-29", "2014-09-01"]

[model.buildings]
ukdale = [1, 2, 5]

[model.buildings.train]
ukdale = [1, 2, 5]

[model.buildings.validation]
ukdale = [1]

[model.buildings.test]
ukdale = [1]

[plot]
f1_lim = [0.4, 1.0]
nde_lim = [0.3, 0.8]
figsize = [4, 3]
num_plots = 10

[plot.appliances]
dish_washer= "Dishwasher"
fridge= "Fridge"
washing_machine= "Washing machine"

[plot.thresh_color]
at = 'b'
mp = 'g'
vs = 'r'
